name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create test directories
      run: |
        mkdir -p tftp
        mkdir -p http

    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sipsak sipcalc

    - name: Run tests
      run: |
        cd tests
        python run_tests.py -v

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          tests/report_*
          tests/test_*/output/* 